server.port=8080

spring.datasource.url= jdbc:postgresql://ep-long-sound-b3svzorv-pooler.c-4.ap-southeast-1.aws.neon.tech/supply-chain-db?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BybjTRu5sl3F
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.scm=DEBUG
logging.level.org.hibernate.SQL=DEBUG
